[package]
name = "gguf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
byteorder = "1.5.0"
clap = { version = "4.4.12", features = ["derive"] }
comfy-table = "7.1.0"
log = "0.4.20"
serde = { version = "1.0.194", features = ["derive"] }
serde_json = { version = "1.0.110", features = ["arbitrary_precision"] }
simple_logger = "4.3.3"
